language: dart
dist: bionic
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor --version
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter pub get
  - flutter pub upgrade
  - flutter packages pub run build_runner build --delete-conflicting-outputs
  - flutter analyze --no-pub --no-current-package lib/
  - flutter build apk
cache:
  directories:
    - $HOME/.pub-cache